# Generated by Django 6.0.5 on 2026-05-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(choices=[('Frontend Development', 'Frontend Development'), ('Backend Development', 'Backend Development'), ('UI/UX Design', 'UI/UX Design'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security')], max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('isactive', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
