# Generated by Django 6.0.5 on 2026-05-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='isactive',
            field=models.BooleanField(),
        ),
    ]
