# Generated by Django 6.0.5 on 2026-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
