# Generated by Django 6.0.5 on 2026-05-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_trainer_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
